from sqlalchemy import TIMESTAMP, ForeignKey, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from multi_doc_chat.src.document_ingestion.data_ingestion import generate_session_id


class Base(DeclarativeBase):
    pass


class Session(Base):
    """
    Chat session model.
    We use a human-readable, time-based ID generated by generate_session_id().
    This ID is also used to:
      - Name FAISS index directory: faiss_index/{session_id}
      - Link chat history
      - Appear in the frontend sidebar (like ChatGPT conversation titles)

    """

    __tablename__ = "sessions"
    id: Mapped[str] = mapped_column(
        String, primary_key=True, default=lambda: generate_session_id
    )
    created_at: Mapped[str] = mapped_column(
        TIMESTAMP, server_default=func.now(), nullable=False
    )


class Message(Base):
    __tablename__ = "messages"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(String, ForeignKey("sessions.id"))
    role: Mapped[str] = mapped_column(String)
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[str] = mapped_column(TIMESTAMP, server_default=func.now())
