from datetime import datetime
from typing import List

from sqlalchemy import TIMESTAMP, ForeignKey, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Session(Base):
    """
    Chat session model.
    We use a human-readable, time-based ID generated by generate_session_id().
    This ID is also used to:
      - Name FAISS index directory: faiss_index/{session_id}
      - Link chat history
      - Appear in the frontend sidebar (like ChatGPT conversation titles)

    """

    __tablename__ = "sessions"
    id: Mapped[str] = mapped_column(String, primary_key=True, index=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP, server_default=func.now(), nullable=False
    )
    messages: Mapped[List["Message"]] = relationship(
        # Back_populates makes it a two-way connection. Between session and messages
        back_populates="session",
        # If a Session is deleted → all Messages linked to it are automatically deleted.
        # No orphan messages exist with no session_id.
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    ingestion_status: Mapped[str] = mapped_column(
        String, default="idle", nullable=False
    )
    files: Mapped[List["UploadedFile"]] = relationship(
        back_populates="session",
        cascade="all , delete-orphan",
        passive_deletes=True,
    )


class Message(Base):
    __tablename__ = "messages"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    session_id: Mapped[str] = mapped_column(
        String,
        ForeignKey("sessions.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    role: Mapped[str] = mapped_column(String)
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP, server_default=func.now())

    # Every Message gets a .session property pointing back to its owning session.
    session: Mapped[Session] = relationship(back_populates="messages")


class UploadedFile(Base):
    __tablename__ = "uploaded_files"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    session_id: Mapped[str] = mapped_column(
        String,
        ForeignKey("sessions.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    filename: Mapped[str] = mapped_column(String)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP, server_default=func.now())

    session: Mapped[Session] = relationship(back_populates="files")


"""
session = await db.get(Session, session_id)
session.messages  # <-- automatically populated by relationship

Your endpoint:

history = await repo.get_history(db, session_id)


works fine, but with relationships you can also:

session = (await db.get(Session, session_id))
for msg in session.messages:
    print(msg.role, msg.content)
"""
